spring:
  application:
    name: focus-local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: admin
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: trace
        type:
          descriptor:
            sql: trace

  contract:
    required-contract-codes:
      - overFourteen
      - privacyPolicy
      - termsOfService
      - useSuperStore

server:
  port: 10001
  servlet:
    context-path: /

